
services:
  db:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: daox_test
    ports:
      - "3307:3306"
    volumes:
      - ./init_mysql.sql:/docker-entrypoint-initdb.d/init_mysql.sql

  pg:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: daox_test
    ports:
      - "5433:5432"
    volumes:
      - ./init_pg.sql:/docker-entrypoint-initdb.d/init_pg.sql