[package]
name = "daox-test"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Integration test suite for the Daox framework."
license.workspace = true
repository.workspace = true
publish = false                                                # Prevent this test suite from being published to crates.io


[dependencies]
# Pour exécuter les requêtes générées par daox
sqlx = { version = "0.9", features = [
    "mysql",
    "postgres",
    "sqlite",
    "runtime-tokio",
    "tls-rustls",
    "chrono",
] }
tokio = { version = "1", features = ["full"] }

# Pour la fonction de lecture sans allocation (Stream)
futures = "0.3"

# Si la BDD contient des dates
chrono = { version = "0.4", features = ["serde"] }

# API & SDK mapping
lightx = { path = "../../lightx-workspace/lightx" }

[build-dependencies]
# daox est utilisé ici pour GÉNÉRER le code pendant le "cargo build"
daox = { path = "../daox", version = "0.2.4" }
tokio = { version = "1", features = ["full"] }
# SQLite est initialisé directement dans le build.rs (création du schéma)
sqlx = { version = "0.9", features = ["sqlite", "runtime-tokio", "tls-rustls"] }
