// =====================================================================
// THIS FILE IS AUTO-GENERATED BY LIGHTX. DO NOT EDIT.
// =====================================================================
#![allow(clippy::needless_borrows_for_generic_args, clippy::collapsible_if)]

pub struct RequestContext {
    pub raw_body: lightx::ext::bytes::Bytes,
    pub global_state: std::sync::Arc<lightx::ext::tokio::sync::broadcast::Sender<lightx::ext::bytes::Bytes>>,
    pub rate_limiter: std::sync::Arc<lightx::ext::moka::sync::Cache<(std::net::IpAddr, &'static str), std::sync::Arc<std::sync::atomic::AtomicU32>>>,
    pub response_cache: std::sync::Arc<lightx::ext::moka::sync::Cache<String, (lightx::ext::hyper::StatusCode, lightx::ext::hyper::HeaderMap, lightx::ext::bytes::Bytes, std::time::Instant)>>,
    pub client_ip: std::net::IpAddr,
    pub user_id: std::option::Option<String>,
    pub headers: lightx::ext::hyper::HeaderMap,
    pub raw_req: Option<lightx::ext::hyper::Request<lightx::ext::hyper::body::Incoming>>,
    pub default_pool: sqlx::MySqlPool,
    pub default_tx: Option<sqlx::Transaction<'static, sqlx::MySql>>,
}

pub struct AppContextFactory {
    pub global_state: std::sync::Arc<lightx::ext::tokio::sync::broadcast::Sender<lightx::ext::bytes::Bytes>>,
    pub rate_limiter: std::sync::Arc<lightx::ext::moka::sync::Cache<(std::net::IpAddr, &'static str), std::sync::Arc<std::sync::atomic::AtomicU32>>>,
    pub response_cache: std::sync::Arc<lightx::ext::moka::sync::Cache<String, (lightx::ext::hyper::StatusCode, lightx::ext::hyper::HeaderMap, lightx::ext::bytes::Bytes, std::time::Instant)>>,
    pub default_pool: sqlx::MySqlPool,
}

impl AppContextFactory {
    pub async fn new() -> Result<Self, lightx::core::AppError> {
        Ok(Self {
            global_state: std::sync::Arc::new(lightx::ext::tokio::sync::broadcast::channel(1024).0),
            rate_limiter: std::sync::Arc::new(lightx::ext::moka::sync::Cache::builder().build()),
            response_cache: std::sync::Arc::new(lightx::ext::moka::sync::Cache::builder().build()),
            default_pool: sqlx::mysql::MySqlPoolOptions::new().connect(&std::env::var("DEFAULT_DATABASE_URL").or_else(|_| std::env::var("DATABASE_URL")).unwrap_or_else(|_| "mysql://root:root@127.0.0.1:3306/my_database".to_string())).await.map_err(|e| lightx::core::AppError::SystemError { msg: e.to_string(), file: file!(), line: line!() })?,
        })
    }
}

impl lightx::server::ContextFactory for AppContextFactory {
    type Context = RequestContext;
    fn create_context(&self, peer_addr: std::net::IpAddr, headers: lightx::ext::hyper::HeaderMap, raw_body: lightx::ext::bytes::Bytes, raw_req: Option<lightx::ext::hyper::Request<lightx::ext::hyper::body::Incoming>>) -> Self::Context {
        let mut client_ip = peer_addr;
        if let Some(xff) = headers.get("x-forwarded-for") {
            if let Ok(s) = xff.to_str() {
                if let Some(first) = s.split(',').next() {
                    if let Ok(parsed) = first.trim().parse() { client_ip = parsed; }
                }
            }
        } else if let Some(xreal) = headers.get("x-real-ip") {
            if let Ok(s) = xreal.to_str() {
                if let Ok(parsed) = s.trim().parse() { client_ip = parsed; }
            }
        }
        RequestContext {
            raw_body,
            global_state: self.global_state.clone(),
            rate_limiter: self.rate_limiter.clone(),
            response_cache: self.response_cache.clone(),
            client_ip,
            user_id: None,
            headers,
            raw_req,
            default_pool: self.default_pool.clone(),
            default_tx: None,
        }
    }

    fn commit_context<'a>(&'a self, ctx: &'a mut Self::Context) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<(), String>> + Send + 'a>> {
        Box::pin(async move {
            if let Some(tx) = ctx.default_tx.take() {
                tx.commit().await.map_err(|e| e.to_string())?;
            }
            Ok(())
        })
    }
}

impl RequestContext {
    pub async fn get_or_create_default_tx(&mut self) -> Result<&mut sqlx::Transaction<'static, sqlx::MySql>, lightx::core::AppError> {
        if self.default_tx.is_none() {
            let tx = self.default_pool.begin().await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
            self.default_tx = Some(tx);
        }
        self.default_tx.as_mut().ok_or_else(|| lightx::core::AppError::SystemError { msg: "Tx absent".to_string(), file: file!(), line: line!() })
    }

    pub async fn commit_default_tx(&mut self) -> Result<(), lightx::core::AppError> {
        if let Some(tx) = self.default_tx.take() {
            tx.commit().await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    pub async fn rollback_default_tx(&mut self) -> Result<(), lightx::core::AppError> {
        if let Some(tx) = self.default_tx.take() {
            tx.rollback().await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }
}

#[derive(Debug, Clone, sqlx::FromRow)]
pub struct ActiveUsers {
    pub email: String,
    pub first_name: Option<String>,
    pub id: i64,
    pub last_name: String,
}

impl ActiveUsers {
    /// Inserts the current record. (Execution uses Pool unless a Transaction is active)
    pub async fn insert(&self, ctx: &mut RequestContext) -> Result<u64, lightx::core::AppError> {
        let mut query = sqlx::query(r#"INSERT INTO active_users (`email`, `first_name`, `id`, `last_name`) VALUES (?, ?, ?, ?)"#);
        query = query.bind(&self.email);
        query = query.bind(&self.first_name);
        query = query.bind(&self.id);
        query = query.bind(&self.last_name);
        let result = if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(result.last_insert_id())
    }

    /// Deletes all records in the table. Returns the number of affected rows.
    pub async fn delete_all(ctx: &mut RequestContext) -> Result<u64, lightx::core::AppError> {
        let query = sqlx::query(r#"DELETE FROM active_users"#);
        let result = if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(result.rows_affected())
    }

    /// Retrieves a paginated list of records. (Zero-Transaction Overhead for pure reads)
    pub async fn find_all(ctx: &mut RequestContext, limit: i64, offset: i64) -> Result<Vec<Self>, lightx::core::AppError> {
        let mut query = sqlx::query_as(r#"SELECT `email`, `first_name`, `id`, `last_name` FROM active_users LIMIT ? OFFSET ?"#);
        query = query.bind(limit).bind(offset);
        let records = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_all(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_all(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(records)
    }

    /// Counts the total number of records in the table.
    pub async fn count(ctx: &mut RequestContext) -> Result<i64, lightx::core::AppError> {
        let query = sqlx::query_scalar::<_, i64>(r#"SELECT COUNT(*) FROM active_users"#);
        let total = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_one(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_one(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(total)
    }

    /// Returns an asynchronous stream to process millions of records without allocating massive memory.
    pub fn stream_all<'a>(ctx: &'a mut RequestContext) -> std::pin::Pin<Box<dyn futures::Stream<Item = Result<Self, lightx::core::AppError>> + Send + 'a>> {
        let query = sqlx::query_as::<_, Self>(r#"SELECT `email`, `first_name`, `id`, `last_name` FROM active_users"#);
        use futures::StreamExt;
        if let Some(tx) = ctx.default_tx.as_mut() {
            let stream = query.fetch(&mut **tx).map(|res| res.map_err(|e| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() }));
            Box::pin(stream)
        } else {
            let stream = query.fetch(&ctx.default_pool).map(|res| res.map_err(|e| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() }));
            Box::pin(stream)
        }
    }

    /// Inserts multiple records in a single atomic transaction. (Batch Insert)
    pub async fn insert_many(items: &[Self], ctx: &mut RequestContext) -> Result<u64, lightx::core::AppError> {
        ctx.get_or_create_default_tx().await?;
        let mut count = 0;
        for item in items {
            item.insert(ctx).await?;
            count += 1;
        }
        Ok(count)
    }

}

#[derive(Debug, Clone, sqlx::FromRow)]
pub struct Configurations {
    pub id: i32,
    pub r#match: Option<String>,
    pub r#type: String,
    pub value: Option<String>,
}

impl Configurations {
    /// Inserts the current record. (Execution uses Pool unless a Transaction is active)
    pub async fn insert(&self, ctx: &mut RequestContext) -> Result<u64, lightx::core::AppError> {
        let mut query = sqlx::query(r#"INSERT INTO configurations (`match`, `type`, `value`) VALUES (?, ?, ?)"#);
        query = query.bind(&self.r#match);
        query = query.bind(&self.r#type);
        query = query.bind(&self.value);
        let result = if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(result.last_insert_id())
    }

    /// Upserts the current record (Insert or Update if PK conflicts).
    pub async fn upsert(&self, ctx: &mut RequestContext) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"INSERT INTO configurations (`match`, `type`, `value`) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE `match` = VALUES(`match`), `type` = VALUES(`type`), `value` = VALUES(`value`)"#);
        query = query.bind(&self.r#match);
        query = query.bind(&self.r#type);
        query = query.bind(&self.value);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    /// Retrieves a record via its primary key. (Zero-Transaction Overhead for pure reads)
    pub async fn get_by_id(ctx: &mut RequestContext, id: i32) -> Result<Option<Self>, lightx::core::AppError> {
        let mut query = sqlx::query_as(r#"SELECT `id`, `match`, `type`, `value` FROM configurations WHERE `id` = ?"#);
        query = query.bind(&id);
        let record = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_optional(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_optional(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(record)
    }

    /// Updates the entire record via its primary key. (Execution uses Pool unless a Transaction is active)
    pub async fn update_by_id(&self, ctx: &mut RequestContext) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"UPDATE configurations SET `match` = ?, `type` = ?, `value` = ? WHERE `id` = ?"#);
        query = query.bind(&self.r#match);
        query = query.bind(&self.r#type);
        query = query.bind(&self.value);
        query = query.bind(&self.id);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    pub async fn update_match(ctx: &mut RequestContext, id: i32, new_val: &str) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"UPDATE configurations SET `match` = ? WHERE `id` = ?"#);
        query = query.bind(new_val);
        query = query.bind(&id);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    pub async fn update_type(ctx: &mut RequestContext, id: i32, new_val: &str) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"UPDATE configurations SET `type` = ? WHERE `id` = ?"#);
        query = query.bind(new_val);
        query = query.bind(&id);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    pub async fn update_value(ctx: &mut RequestContext, id: i32, new_val: &str) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"UPDATE configurations SET `value` = ? WHERE `id` = ?"#);
        query = query.bind(new_val);
        query = query.bind(&id);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    /// Permanently deletes the record. (Execution uses Pool unless a Transaction is active)
    pub async fn delete_by_id(ctx: &mut RequestContext, id: i32) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"DELETE FROM configurations WHERE `id` = ?"#);
        query = query.bind(&id);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    /// Deletes all records in the table. Returns the number of affected rows.
    pub async fn delete_all(ctx: &mut RequestContext) -> Result<u64, lightx::core::AppError> {
        let query = sqlx::query(r#"DELETE FROM configurations"#);
        let result = if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(result.rows_affected())
    }

    /// Retrieves a paginated list of records. (Zero-Transaction Overhead for pure reads)
    pub async fn find_all(ctx: &mut RequestContext, limit: i64, offset: i64) -> Result<Vec<Self>, lightx::core::AppError> {
        let mut query = sqlx::query_as(r#"SELECT `id`, `match`, `type`, `value` FROM configurations LIMIT ? OFFSET ?"#);
        query = query.bind(limit).bind(offset);
        let records = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_all(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_all(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(records)
    }

    /// Checks if a record exists by its primary key. (Ultra-fast, doesn't fetch columns)
    pub async fn exists_by_id(ctx: &mut RequestContext, id: i32) -> Result<bool, lightx::core::AppError> {
        let mut query = sqlx::query(r#"SELECT 1 FROM configurations WHERE `id` = ?"#);
        query = query.bind(&id);
        let record = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_optional(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_optional(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(record.is_some())
    }

    /// High-performance O(1) Keyset Pagination based on the Primary Key.
    pub async fn list_by_id_cursor(ctx: &mut RequestContext, last_id: Option<i32>, limit: i64) -> Result<Vec<Self>, lightx::core::AppError> {
        let base_query = if last_id.is_some() {
            r#"SELECT `id`, `match`, `type`, `value` FROM configurations WHERE `id` > ? ORDER BY `id` ASC LIMIT ?"#
        } else {
            r#"SELECT `id`, `match`, `type`, `value` FROM configurations ORDER BY `id` ASC LIMIT ?"#
        };
        let mut query = sqlx::query_as(base_query);
        if let Some(last_val) = last_id {
            query = query.bind(last_val);
        }
        query = query.bind(limit);
        let records = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_all(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_all(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(records)
    }

    /// Counts the total number of records in the table.
    pub async fn count(ctx: &mut RequestContext) -> Result<i64, lightx::core::AppError> {
        let query = sqlx::query_scalar::<_, i64>(r#"SELECT COUNT(*) FROM configurations"#);
        let total = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_one(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_one(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(total)
    }

    /// Returns an asynchronous stream to process millions of records without allocating massive memory.
    pub fn stream_all<'a>(ctx: &'a mut RequestContext) -> std::pin::Pin<Box<dyn futures::Stream<Item = Result<Self, lightx::core::AppError>> + Send + 'a>> {
        let query = sqlx::query_as::<_, Self>(r#"SELECT `id`, `match`, `type`, `value` FROM configurations"#);
        use futures::StreamExt;
        if let Some(tx) = ctx.default_tx.as_mut() {
            let stream = query.fetch(&mut **tx).map(|res| res.map_err(|e| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() }));
            Box::pin(stream)
        } else {
            let stream = query.fetch(&ctx.default_pool).map(|res| res.map_err(|e| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() }));
            Box::pin(stream)
        }
    }

    /// Inserts multiple records in a single atomic transaction. (Batch Insert)
    pub async fn insert_many(items: &[Self], ctx: &mut RequestContext) -> Result<u64, lightx::core::AppError> {
        ctx.get_or_create_default_tx().await?;
        let mut count = 0;
        for item in items {
            item.insert(ctx).await?;
            count += 1;
        }
        Ok(count)
    }

    /// Upserts multiple records in a single atomic transaction. (Batch Upsert)
    pub async fn upsert_many(items: &[Self], ctx: &mut RequestContext) -> Result<(), lightx::core::AppError> {
        ctx.get_or_create_default_tx().await?;
        for item in items {
            item.upsert(ctx).await?;
        }
        Ok(())
    }

}

#[derive(Debug, Clone, sqlx::FromRow)]
pub struct Currencies {
    pub code: String,
    pub name: String,
}

impl Currencies {
    /// Inserts the current record. (Execution uses Pool unless a Transaction is active)
    pub async fn insert(&self, ctx: &mut RequestContext) -> Result<u64, lightx::core::AppError> {
        let mut query = sqlx::query(r#"INSERT INTO currencies (`code`, `name`) VALUES (?, ?)"#);
        query = query.bind(&self.code);
        query = query.bind(&self.name);
        let result = if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(result.last_insert_id())
    }

    /// Upserts the current record (Insert or Update if PK conflicts).
    pub async fn upsert(&self, ctx: &mut RequestContext) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"INSERT INTO currencies (`code`, `name`) VALUES (?, ?) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`)"#);
        query = query.bind(&self.code);
        query = query.bind(&self.name);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    /// Retrieves a record via its primary key. (Zero-Transaction Overhead for pure reads)
    pub async fn get_by_code(ctx: &mut RequestContext, code: &str) -> Result<Option<Self>, lightx::core::AppError> {
        let mut query = sqlx::query_as(r#"SELECT `code`, `name` FROM currencies WHERE `code` = ?"#);
        query = query.bind(code);
        let record = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_optional(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_optional(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(record)
    }

    /// Updates the entire record via its primary key. (Execution uses Pool unless a Transaction is active)
    pub async fn update_by_code(&self, ctx: &mut RequestContext) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"UPDATE currencies SET `name` = ? WHERE `code` = ?"#);
        query = query.bind(&self.name);
        query = query.bind(&self.code);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    pub async fn update_name(ctx: &mut RequestContext, code: &str, new_val: &str) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"UPDATE currencies SET `name` = ? WHERE `code` = ?"#);
        query = query.bind(new_val);
        query = query.bind(code);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    /// Permanently deletes the record. (Execution uses Pool unless a Transaction is active)
    pub async fn delete_by_code(ctx: &mut RequestContext, code: &str) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"DELETE FROM currencies WHERE `code` = ?"#);
        query = query.bind(code);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    /// Deletes all records in the table. Returns the number of affected rows.
    pub async fn delete_all(ctx: &mut RequestContext) -> Result<u64, lightx::core::AppError> {
        let query = sqlx::query(r#"DELETE FROM currencies"#);
        let result = if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(result.rows_affected())
    }

    /// Retrieves a paginated list of records. (Zero-Transaction Overhead for pure reads)
    pub async fn find_all(ctx: &mut RequestContext, limit: i64, offset: i64) -> Result<Vec<Self>, lightx::core::AppError> {
        let mut query = sqlx::query_as(r#"SELECT `code`, `name` FROM currencies LIMIT ? OFFSET ?"#);
        query = query.bind(limit).bind(offset);
        let records = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_all(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_all(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(records)
    }

    /// Checks if a record exists by its primary key. (Ultra-fast, doesn't fetch columns)
    pub async fn exists_by_code(ctx: &mut RequestContext, code: &str) -> Result<bool, lightx::core::AppError> {
        let mut query = sqlx::query(r#"SELECT 1 FROM currencies WHERE `code` = ?"#);
        query = query.bind(code);
        let record = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_optional(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_optional(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(record.is_some())
    }

    /// High-performance O(1) Keyset Pagination based on the Primary Key.
    pub async fn list_by_code_cursor(ctx: &mut RequestContext, last_code: Option<String>, limit: i64) -> Result<Vec<Self>, lightx::core::AppError> {
        let base_query = if last_code.is_some() {
            r#"SELECT `code`, `name` FROM currencies WHERE `code` > ? ORDER BY `code` ASC LIMIT ?"#
        } else {
            r#"SELECT `code`, `name` FROM currencies ORDER BY `code` ASC LIMIT ?"#
        };
        let mut query = sqlx::query_as(base_query);
        if let Some(last_val) = last_code {
            query = query.bind(last_val);
        }
        query = query.bind(limit);
        let records = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_all(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_all(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(records)
    }

    /// Counts the total number of records in the table.
    pub async fn count(ctx: &mut RequestContext) -> Result<i64, lightx::core::AppError> {
        let query = sqlx::query_scalar::<_, i64>(r#"SELECT COUNT(*) FROM currencies"#);
        let total = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_one(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_one(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(total)
    }

    /// Returns an asynchronous stream to process millions of records without allocating massive memory.
    pub fn stream_all<'a>(ctx: &'a mut RequestContext) -> std::pin::Pin<Box<dyn futures::Stream<Item = Result<Self, lightx::core::AppError>> + Send + 'a>> {
        let query = sqlx::query_as::<_, Self>(r#"SELECT `code`, `name` FROM currencies"#);
        use futures::StreamExt;
        if let Some(tx) = ctx.default_tx.as_mut() {
            let stream = query.fetch(&mut **tx).map(|res| res.map_err(|e| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() }));
            Box::pin(stream)
        } else {
            let stream = query.fetch(&ctx.default_pool).map(|res| res.map_err(|e| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() }));
            Box::pin(stream)
        }
    }

    /// Inserts multiple records in a single atomic transaction. (Batch Insert)
    pub async fn insert_many(items: &[Self], ctx: &mut RequestContext) -> Result<u64, lightx::core::AppError> {
        ctx.get_or_create_default_tx().await?;
        let mut count = 0;
        for item in items {
            item.insert(ctx).await?;
            count += 1;
        }
        Ok(count)
    }

    /// Upserts multiple records in a single atomic transaction. (Batch Upsert)
    pub async fn upsert_many(items: &[Self], ctx: &mut RequestContext) -> Result<(), lightx::core::AppError> {
        ctx.get_or_create_default_tx().await?;
        for item in items {
            item.upsert(ctx).await?;
        }
        Ok(())
    }

}

#[derive(Debug, Clone, sqlx::FromRow)]
pub struct OrderItems {
    pub order_id: i64,
    pub product_id: i64,
    pub quantity: i32,
}

impl OrderItems {
    /// Inserts the current record. (Execution uses Pool unless a Transaction is active)
    pub async fn insert(&self, ctx: &mut RequestContext) -> Result<u64, lightx::core::AppError> {
        let mut query = sqlx::query(r#"INSERT INTO order_items (`order_id`, `product_id`, `quantity`) VALUES (?, ?, ?)"#);
        query = query.bind(&self.order_id);
        query = query.bind(&self.product_id);
        query = query.bind(&self.quantity);
        let result = if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(result.last_insert_id())
    }

    /// Upserts the current record (Insert or Update if PK conflicts).
    pub async fn upsert(&self, ctx: &mut RequestContext) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"INSERT INTO order_items (`order_id`, `product_id`, `quantity`) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE `quantity` = VALUES(`quantity`)"#);
        query = query.bind(&self.order_id);
        query = query.bind(&self.product_id);
        query = query.bind(&self.quantity);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    /// Retrieves a record via its primary key. (Zero-Transaction Overhead for pure reads)
    pub async fn get_by_order_id_and_product_id(ctx: &mut RequestContext, order_id: i64, product_id: i64) -> Result<Option<Self>, lightx::core::AppError> {
        let mut query = sqlx::query_as(r#"SELECT `order_id`, `product_id`, `quantity` FROM order_items WHERE `order_id` = ? AND `product_id` = ?"#);
        query = query.bind(&order_id);
        query = query.bind(&product_id);
        let record = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_optional(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_optional(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(record)
    }

    /// Updates the entire record via its primary key. (Execution uses Pool unless a Transaction is active)
    pub async fn update_by_order_id_and_product_id(&self, ctx: &mut RequestContext) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"UPDATE order_items SET `quantity` = ? WHERE `order_id` = ? AND `product_id` = ?"#);
        query = query.bind(&self.quantity);
        query = query.bind(&self.order_id);
        query = query.bind(&self.product_id);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    pub async fn update_quantity(ctx: &mut RequestContext, order_id: i64, product_id: i64, new_val: i32) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"UPDATE order_items SET `quantity` = ? WHERE `order_id` = ? AND `product_id` = ?"#);
        query = query.bind(&new_val);
        query = query.bind(&order_id);
        query = query.bind(&product_id);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    /// Permanently deletes the record. (Execution uses Pool unless a Transaction is active)
    pub async fn delete_by_order_id_and_product_id(ctx: &mut RequestContext, order_id: i64, product_id: i64) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"DELETE FROM order_items WHERE `order_id` = ? AND `product_id` = ?"#);
        query = query.bind(&order_id);
        query = query.bind(&product_id);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    /// Deletes all records in the table. Returns the number of affected rows.
    pub async fn delete_all(ctx: &mut RequestContext) -> Result<u64, lightx::core::AppError> {
        let query = sqlx::query(r#"DELETE FROM order_items"#);
        let result = if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(result.rows_affected())
    }

    /// Retrieves a paginated list of records. (Zero-Transaction Overhead for pure reads)
    pub async fn find_all(ctx: &mut RequestContext, limit: i64, offset: i64) -> Result<Vec<Self>, lightx::core::AppError> {
        let mut query = sqlx::query_as(r#"SELECT `order_id`, `product_id`, `quantity` FROM order_items LIMIT ? OFFSET ?"#);
        query = query.bind(limit).bind(offset);
        let records = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_all(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_all(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(records)
    }

    /// Checks if a record exists by its primary key. (Ultra-fast, doesn't fetch columns)
    pub async fn exists_by_order_id_and_product_id(ctx: &mut RequestContext, order_id: i64, product_id: i64) -> Result<bool, lightx::core::AppError> {
        let mut query = sqlx::query(r#"SELECT 1 FROM order_items WHERE `order_id` = ? AND `product_id` = ?"#);
        query = query.bind(&order_id);
        query = query.bind(&product_id);
        let record = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_optional(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_optional(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(record.is_some())
    }

    /// Counts the total number of records in the table.
    pub async fn count(ctx: &mut RequestContext) -> Result<i64, lightx::core::AppError> {
        let query = sqlx::query_scalar::<_, i64>(r#"SELECT COUNT(*) FROM order_items"#);
        let total = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_one(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_one(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(total)
    }

    /// Returns an asynchronous stream to process millions of records without allocating massive memory.
    pub fn stream_all<'a>(ctx: &'a mut RequestContext) -> std::pin::Pin<Box<dyn futures::Stream<Item = Result<Self, lightx::core::AppError>> + Send + 'a>> {
        let query = sqlx::query_as::<_, Self>(r#"SELECT `order_id`, `product_id`, `quantity` FROM order_items"#);
        use futures::StreamExt;
        if let Some(tx) = ctx.default_tx.as_mut() {
            let stream = query.fetch(&mut **tx).map(|res| res.map_err(|e| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() }));
            Box::pin(stream)
        } else {
            let stream = query.fetch(&ctx.default_pool).map(|res| res.map_err(|e| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() }));
            Box::pin(stream)
        }
    }

    /// Inserts multiple records in a single atomic transaction. (Batch Insert)
    pub async fn insert_many(items: &[Self], ctx: &mut RequestContext) -> Result<u64, lightx::core::AppError> {
        ctx.get_or_create_default_tx().await?;
        let mut count = 0;
        for item in items {
            item.insert(ctx).await?;
            count += 1;
        }
        Ok(count)
    }

    /// Upserts multiple records in a single atomic transaction. (Batch Upsert)
    pub async fn upsert_many(items: &[Self], ctx: &mut RequestContext) -> Result<(), lightx::core::AppError> {
        ctx.get_or_create_default_tx().await?;
        for item in items {
            item.upsert(ctx).await?;
        }
        Ok(())
    }

}

#[derive(Debug, Clone, sqlx::FromRow)]
pub struct ProductMetadata {
    pub attributes: Option<String>,
    pub category: String,
    pub id: Vec<u8>,
    pub raw_data: Option<Vec<u8>>,
}

impl ProductMetadata {
    /// Inserts the current record. (Execution uses Pool unless a Transaction is active)
    pub async fn insert(&self, ctx: &mut RequestContext) -> Result<u64, lightx::core::AppError> {
        let mut query = sqlx::query(r#"INSERT INTO product_metadata (`attributes`, `category`, `id`, `raw_data`) VALUES (?, ?, ?, ?)"#);
        query = query.bind(&self.attributes);
        query = query.bind(&self.category);
        query = query.bind(&self.id);
        query = query.bind(&self.raw_data);
        let result = if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(result.last_insert_id())
    }

    /// Upserts the current record (Insert or Update if PK conflicts).
    pub async fn upsert(&self, ctx: &mut RequestContext) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"INSERT INTO product_metadata (`attributes`, `category`, `id`, `raw_data`) VALUES (?, ?, ?, ?) ON DUPLICATE KEY UPDATE `attributes` = VALUES(`attributes`), `category` = VALUES(`category`), `raw_data` = VALUES(`raw_data`)"#);
        query = query.bind(&self.attributes);
        query = query.bind(&self.category);
        query = query.bind(&self.id);
        query = query.bind(&self.raw_data);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    /// Retrieves a record via its primary key. (Zero-Transaction Overhead for pure reads)
    pub async fn get_by_id(ctx: &mut RequestContext, id: &[u8]) -> Result<Option<Self>, lightx::core::AppError> {
        let mut query = sqlx::query_as(r#"SELECT `attributes`, `category`, `id`, `raw_data` FROM product_metadata WHERE `id` = ?"#);
        query = query.bind(id);
        let record = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_optional(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_optional(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(record)
    }

    /// Updates the entire record via its primary key. (Execution uses Pool unless a Transaction is active)
    pub async fn update_by_id(&self, ctx: &mut RequestContext) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"UPDATE product_metadata SET `attributes` = ?, `category` = ?, `raw_data` = ? WHERE `id` = ?"#);
        query = query.bind(&self.attributes);
        query = query.bind(&self.category);
        query = query.bind(&self.raw_data);
        query = query.bind(&self.id);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    pub async fn update_attributes(ctx: &mut RequestContext, id: &[u8], new_val: &str) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"UPDATE product_metadata SET `attributes` = ? WHERE `id` = ?"#);
        query = query.bind(new_val);
        query = query.bind(id);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    pub async fn update_category(ctx: &mut RequestContext, id: &[u8], new_val: &str) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"UPDATE product_metadata SET `category` = ? WHERE `id` = ?"#);
        query = query.bind(new_val);
        query = query.bind(id);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    pub async fn update_raw_data(ctx: &mut RequestContext, id: &[u8], new_val: &[u8]) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"UPDATE product_metadata SET `raw_data` = ? WHERE `id` = ?"#);
        query = query.bind(new_val);
        query = query.bind(id);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    /// Permanently deletes the record. (Execution uses Pool unless a Transaction is active)
    pub async fn delete_by_id(ctx: &mut RequestContext, id: &[u8]) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"DELETE FROM product_metadata WHERE `id` = ?"#);
        query = query.bind(id);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    /// Deletes all records in the table. Returns the number of affected rows.
    pub async fn delete_all(ctx: &mut RequestContext) -> Result<u64, lightx::core::AppError> {
        let query = sqlx::query(r#"DELETE FROM product_metadata"#);
        let result = if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(result.rows_affected())
    }

    /// Retrieves a paginated list of records. (Zero-Transaction Overhead for pure reads)
    pub async fn find_all(ctx: &mut RequestContext, limit: i64, offset: i64) -> Result<Vec<Self>, lightx::core::AppError> {
        let mut query = sqlx::query_as(r#"SELECT `attributes`, `category`, `id`, `raw_data` FROM product_metadata LIMIT ? OFFSET ?"#);
        query = query.bind(limit).bind(offset);
        let records = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_all(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_all(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(records)
    }

    /// Checks if a record exists by its primary key. (Ultra-fast, doesn't fetch columns)
    pub async fn exists_by_id(ctx: &mut RequestContext, id: &[u8]) -> Result<bool, lightx::core::AppError> {
        let mut query = sqlx::query(r#"SELECT 1 FROM product_metadata WHERE `id` = ?"#);
        query = query.bind(id);
        let record = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_optional(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_optional(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(record.is_some())
    }

    /// High-performance O(1) Keyset Pagination based on the Primary Key.
    pub async fn list_by_id_cursor(ctx: &mut RequestContext, last_id: Option<Vec<u8>>, limit: i64) -> Result<Vec<Self>, lightx::core::AppError> {
        let base_query = if last_id.is_some() {
            r#"SELECT `attributes`, `category`, `id`, `raw_data` FROM product_metadata WHERE `id` > ? ORDER BY `id` ASC LIMIT ?"#
        } else {
            r#"SELECT `attributes`, `category`, `id`, `raw_data` FROM product_metadata ORDER BY `id` ASC LIMIT ?"#
        };
        let mut query = sqlx::query_as(base_query);
        if let Some(last_val) = last_id {
            query = query.bind(last_val);
        }
        query = query.bind(limit);
        let records = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_all(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_all(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(records)
    }

    /// Counts the total number of records in the table.
    pub async fn count(ctx: &mut RequestContext) -> Result<i64, lightx::core::AppError> {
        let query = sqlx::query_scalar::<_, i64>(r#"SELECT COUNT(*) FROM product_metadata"#);
        let total = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_one(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_one(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(total)
    }

    /// Returns an asynchronous stream to process millions of records without allocating massive memory.
    pub fn stream_all<'a>(ctx: &'a mut RequestContext) -> std::pin::Pin<Box<dyn futures::Stream<Item = Result<Self, lightx::core::AppError>> + Send + 'a>> {
        let query = sqlx::query_as::<_, Self>(r#"SELECT `attributes`, `category`, `id`, `raw_data` FROM product_metadata"#);
        use futures::StreamExt;
        if let Some(tx) = ctx.default_tx.as_mut() {
            let stream = query.fetch(&mut **tx).map(|res| res.map_err(|e| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() }));
            Box::pin(stream)
        } else {
            let stream = query.fetch(&ctx.default_pool).map(|res| res.map_err(|e| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() }));
            Box::pin(stream)
        }
    }

    /// Inserts multiple records in a single atomic transaction. (Batch Insert)
    pub async fn insert_many(items: &[Self], ctx: &mut RequestContext) -> Result<u64, lightx::core::AppError> {
        ctx.get_or_create_default_tx().await?;
        let mut count = 0;
        for item in items {
            item.insert(ctx).await?;
            count += 1;
        }
        Ok(count)
    }

    /// Upserts multiple records in a single atomic transaction. (Batch Upsert)
    pub async fn upsert_many(items: &[Self], ctx: &mut RequestContext) -> Result<(), lightx::core::AppError> {
        ctx.get_or_create_default_tx().await?;
        for item in items {
            item.upsert(ctx).await?;
        }
        Ok(())
    }

}

#[derive(Debug, Clone, sqlx::FromRow)]
pub struct UserRoles {
    pub assigned_at: Option<chrono::DateTime<chrono::Utc>>,
    pub role_name: String,
    pub user_id: i64,
}

impl UserRoles {
    /// Inserts the current record. (Execution uses Pool unless a Transaction is active)
    pub async fn insert(&self, ctx: &mut RequestContext) -> Result<u64, lightx::core::AppError> {
        let mut query = sqlx::query(r#"INSERT INTO user_roles (`assigned_at`, `role_name`, `user_id`) VALUES (?, ?, ?)"#);
        query = query.bind(&self.assigned_at);
        query = query.bind(&self.role_name);
        query = query.bind(&self.user_id);
        let result = if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(result.last_insert_id())
    }

    /// Upserts the current record (Insert or Update if PK conflicts).
    pub async fn upsert(&self, ctx: &mut RequestContext) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"INSERT INTO user_roles (`assigned_at`, `role_name`, `user_id`) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE `assigned_at` = VALUES(`assigned_at`)"#);
        query = query.bind(&self.assigned_at);
        query = query.bind(&self.role_name);
        query = query.bind(&self.user_id);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    /// Retrieves a record via its primary key. (Zero-Transaction Overhead for pure reads)
    pub async fn get_by_role_name_and_user_id(ctx: &mut RequestContext, role_name: &str, user_id: i64) -> Result<Option<Self>, lightx::core::AppError> {
        let mut query = sqlx::query_as(r#"SELECT `assigned_at`, `role_name`, `user_id` FROM user_roles WHERE `role_name` = ? AND `user_id` = ?"#);
        query = query.bind(role_name);
        query = query.bind(&user_id);
        let record = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_optional(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_optional(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(record)
    }

    /// Updates the entire record via its primary key. (Execution uses Pool unless a Transaction is active)
    pub async fn update_by_role_name_and_user_id(&self, ctx: &mut RequestContext) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"UPDATE user_roles SET `assigned_at` = ? WHERE `role_name` = ? AND `user_id` = ?"#);
        query = query.bind(&self.assigned_at);
        query = query.bind(&self.role_name);
        query = query.bind(&self.user_id);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    pub async fn update_assigned_at(ctx: &mut RequestContext, role_name: &str, user_id: i64, new_val: chrono::DateTime<chrono::Utc>) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"UPDATE user_roles SET `assigned_at` = ? WHERE `role_name` = ? AND `user_id` = ?"#);
        query = query.bind(&new_val);
        query = query.bind(role_name);
        query = query.bind(&user_id);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    /// Permanently deletes the record. (Execution uses Pool unless a Transaction is active)
    pub async fn delete_by_role_name_and_user_id(ctx: &mut RequestContext, role_name: &str, user_id: i64) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"DELETE FROM user_roles WHERE `role_name` = ? AND `user_id` = ?"#);
        query = query.bind(role_name);
        query = query.bind(&user_id);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    /// Deletes all records in the table. Returns the number of affected rows.
    pub async fn delete_all(ctx: &mut RequestContext) -> Result<u64, lightx::core::AppError> {
        let query = sqlx::query(r#"DELETE FROM user_roles"#);
        let result = if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(result.rows_affected())
    }

    /// Retrieves a paginated list of records. (Zero-Transaction Overhead for pure reads)
    pub async fn find_all(ctx: &mut RequestContext, limit: i64, offset: i64) -> Result<Vec<Self>, lightx::core::AppError> {
        let mut query = sqlx::query_as(r#"SELECT `assigned_at`, `role_name`, `user_id` FROM user_roles LIMIT ? OFFSET ?"#);
        query = query.bind(limit).bind(offset);
        let records = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_all(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_all(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(records)
    }

    /// Checks if a record exists by its primary key. (Ultra-fast, doesn't fetch columns)
    pub async fn exists_by_role_name_and_user_id(ctx: &mut RequestContext, role_name: &str, user_id: i64) -> Result<bool, lightx::core::AppError> {
        let mut query = sqlx::query(r#"SELECT 1 FROM user_roles WHERE `role_name` = ? AND `user_id` = ?"#);
        query = query.bind(role_name);
        query = query.bind(&user_id);
        let record = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_optional(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_optional(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(record.is_some())
    }

    /// Counts the total number of records in the table.
    pub async fn count(ctx: &mut RequestContext) -> Result<i64, lightx::core::AppError> {
        let query = sqlx::query_scalar::<_, i64>(r#"SELECT COUNT(*) FROM user_roles"#);
        let total = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_one(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_one(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(total)
    }

    /// Returns an asynchronous stream to process millions of records without allocating massive memory.
    pub fn stream_all<'a>(ctx: &'a mut RequestContext) -> std::pin::Pin<Box<dyn futures::Stream<Item = Result<Self, lightx::core::AppError>> + Send + 'a>> {
        let query = sqlx::query_as::<_, Self>(r#"SELECT `assigned_at`, `role_name`, `user_id` FROM user_roles"#);
        use futures::StreamExt;
        if let Some(tx) = ctx.default_tx.as_mut() {
            let stream = query.fetch(&mut **tx).map(|res| res.map_err(|e| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() }));
            Box::pin(stream)
        } else {
            let stream = query.fetch(&ctx.default_pool).map(|res| res.map_err(|e| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() }));
            Box::pin(stream)
        }
    }

    /// Inserts multiple records in a single atomic transaction. (Batch Insert)
    pub async fn insert_many(items: &[Self], ctx: &mut RequestContext) -> Result<u64, lightx::core::AppError> {
        ctx.get_or_create_default_tx().await?;
        let mut count = 0;
        for item in items {
            item.insert(ctx).await?;
            count += 1;
        }
        Ok(count)
    }

    /// Upserts multiple records in a single atomic transaction. (Batch Upsert)
    pub async fn upsert_many(items: &[Self], ctx: &mut RequestContext) -> Result<(), lightx::core::AppError> {
        ctx.get_or_create_default_tx().await?;
        for item in items {
            item.upsert(ctx).await?;
        }
        Ok(())
    }

    /// Retrieves records by index `idx_user_id`.
    pub async fn get_by_user_id(ctx: &mut RequestContext, user_id: i64) -> Result<Vec<Self>, lightx::core::AppError> {
        let mut query = sqlx::query_as(r#"SELECT `assigned_at`, `role_name`, `user_id` FROM user_roles WHERE `user_id` = ?"#);
        query = query.bind(&user_id);
        let records = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_all(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_all(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(records)
    }

    /// Safely streams records by index `idx_user_id`.
    pub fn stream_by_user_id<'a>(ctx: &'a mut RequestContext, user_id: i64) -> std::pin::Pin<Box<dyn futures::Stream<Item = Result<Self, lightx::core::AppError>> + Send + 'a>> {
        let mut query = sqlx::query_as::<_, Self>(r#"SELECT `assigned_at`, `role_name`, `user_id` FROM user_roles WHERE `user_id` = ?"#);
        query = query.bind(user_id);
        use futures::StreamExt;
        if let Some(tx) = ctx.default_tx.as_mut() {
            let stream = query.fetch(&mut **tx).map(|res| res.map_err(|e| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() }));
            Box::pin(stream)
        } else {
            let stream = query.fetch(&ctx.default_pool).map(|res| res.map_err(|e| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() }));
            Box::pin(stream)
        }
    }

    /// Deletes records matching the index `idx_user_id`.
    pub async fn delete_by_user_id(ctx: &mut RequestContext, user_id: i64) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"DELETE FROM user_roles WHERE `user_id` = ?"#);
        query = query.bind(&user_id);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    /// Retrieves records by index `idx_user_role`.
    pub async fn get_by_user_id_and_role_name(ctx: &mut RequestContext, user_id: i64, role_name: &str) -> Result<Option<Self>, lightx::core::AppError> {
        let mut query = sqlx::query_as(r#"SELECT `assigned_at`, `role_name`, `user_id` FROM user_roles WHERE `user_id` = ? AND `role_name` = ?"#);
        query = query.bind(&user_id);
        query = query.bind(role_name);
        let records = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_optional(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_optional(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(records)
    }

    /// Deletes records matching the index `idx_user_role`.
    pub async fn delete_by_user_id_and_role_name(ctx: &mut RequestContext, user_id: i64, role_name: &str) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"DELETE FROM user_roles WHERE `user_id` = ? AND `role_name` = ?"#);
        query = query.bind(&user_id);
        query = query.bind(role_name);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

}

#[derive(Debug, Clone, sqlx::FromRow)]
pub struct Users {
    pub created_at: Option<chrono::DateTime<chrono::Utc>>,
    pub email: String,
    pub first_name: Option<String>,
    pub id: i64,
    pub last_name: String,
    pub status: String,
}

impl Users {
    /// Inserts the current record. (Execution uses Pool unless a Transaction is active)
    pub async fn insert(&self, ctx: &mut RequestContext) -> Result<u64, lightx::core::AppError> {
        let mut query = sqlx::query(r#"INSERT INTO users (`created_at`, `email`, `first_name`, `last_name`, `status`) VALUES (?, ?, ?, ?, ?)"#);
        query = query.bind(&self.created_at);
        query = query.bind(&self.email);
        query = query.bind(&self.first_name);
        query = query.bind(&self.last_name);
        query = query.bind(&self.status);
        let result = if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(result.last_insert_id())
    }

    /// Upserts the current record (Insert or Update if PK conflicts).
    pub async fn upsert(&self, ctx: &mut RequestContext) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"INSERT INTO users (`created_at`, `email`, `first_name`, `last_name`, `status`) VALUES (?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE `created_at` = VALUES(`created_at`), `email` = VALUES(`email`), `first_name` = VALUES(`first_name`), `last_name` = VALUES(`last_name`), `status` = VALUES(`status`)"#);
        query = query.bind(&self.created_at);
        query = query.bind(&self.email);
        query = query.bind(&self.first_name);
        query = query.bind(&self.last_name);
        query = query.bind(&self.status);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    /// Retrieves a record via its primary key. (Zero-Transaction Overhead for pure reads)
    pub async fn get_by_id(ctx: &mut RequestContext, id: i64) -> Result<Option<Self>, lightx::core::AppError> {
        let mut query = sqlx::query_as(r#"SELECT `created_at`, `email`, `first_name`, `id`, `last_name`, `status` FROM users WHERE `id` = ?"#);
        query = query.bind(&id);
        let record = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_optional(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_optional(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(record)
    }

    /// Updates the entire record via its primary key. (Execution uses Pool unless a Transaction is active)
    pub async fn update_by_id(&self, ctx: &mut RequestContext) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"UPDATE users SET `created_at` = ?, `email` = ?, `first_name` = ?, `last_name` = ?, `status` = ? WHERE `id` = ?"#);
        query = query.bind(&self.created_at);
        query = query.bind(&self.email);
        query = query.bind(&self.first_name);
        query = query.bind(&self.last_name);
        query = query.bind(&self.status);
        query = query.bind(&self.id);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    pub async fn update_created_at(ctx: &mut RequestContext, id: i64, new_val: chrono::DateTime<chrono::Utc>) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"UPDATE users SET `created_at` = ? WHERE `id` = ?"#);
        query = query.bind(&new_val);
        query = query.bind(&id);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    pub async fn update_email(ctx: &mut RequestContext, id: i64, new_val: &str) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"UPDATE users SET `email` = ? WHERE `id` = ?"#);
        query = query.bind(new_val);
        query = query.bind(&id);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    pub async fn update_first_name(ctx: &mut RequestContext, id: i64, new_val: &str) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"UPDATE users SET `first_name` = ? WHERE `id` = ?"#);
        query = query.bind(new_val);
        query = query.bind(&id);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    pub async fn update_last_name(ctx: &mut RequestContext, id: i64, new_val: &str) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"UPDATE users SET `last_name` = ? WHERE `id` = ?"#);
        query = query.bind(new_val);
        query = query.bind(&id);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    pub async fn update_status(ctx: &mut RequestContext, id: i64, new_val: &str) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"UPDATE users SET `status` = ? WHERE `id` = ?"#);
        query = query.bind(new_val);
        query = query.bind(&id);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    /// Permanently deletes the record. (Execution uses Pool unless a Transaction is active)
    pub async fn delete_by_id(ctx: &mut RequestContext, id: i64) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"DELETE FROM users WHERE `id` = ?"#);
        query = query.bind(&id);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    /// Deletes all records in the table. Returns the number of affected rows.
    pub async fn delete_all(ctx: &mut RequestContext) -> Result<u64, lightx::core::AppError> {
        let query = sqlx::query(r#"DELETE FROM users"#);
        let result = if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(result.rows_affected())
    }

    /// Retrieves a paginated list of records. (Zero-Transaction Overhead for pure reads)
    pub async fn find_all(ctx: &mut RequestContext, limit: i64, offset: i64) -> Result<Vec<Self>, lightx::core::AppError> {
        let mut query = sqlx::query_as(r#"SELECT `created_at`, `email`, `first_name`, `id`, `last_name`, `status` FROM users LIMIT ? OFFSET ?"#);
        query = query.bind(limit).bind(offset);
        let records = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_all(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_all(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(records)
    }

    /// Checks if a record exists by its primary key. (Ultra-fast, doesn't fetch columns)
    pub async fn exists_by_id(ctx: &mut RequestContext, id: i64) -> Result<bool, lightx::core::AppError> {
        let mut query = sqlx::query(r#"SELECT 1 FROM users WHERE `id` = ?"#);
        query = query.bind(&id);
        let record = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_optional(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_optional(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(record.is_some())
    }

    /// High-performance O(1) Keyset Pagination based on the Primary Key.
    pub async fn list_by_id_cursor(ctx: &mut RequestContext, last_id: Option<i64>, limit: i64) -> Result<Vec<Self>, lightx::core::AppError> {
        let base_query = if last_id.is_some() {
            r#"SELECT `created_at`, `email`, `first_name`, `id`, `last_name`, `status` FROM users WHERE `id` > ? ORDER BY `id` ASC LIMIT ?"#
        } else {
            r#"SELECT `created_at`, `email`, `first_name`, `id`, `last_name`, `status` FROM users ORDER BY `id` ASC LIMIT ?"#
        };
        let mut query = sqlx::query_as(base_query);
        if let Some(last_val) = last_id {
            query = query.bind(last_val);
        }
        query = query.bind(limit);
        let records = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_all(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_all(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(records)
    }

    /// Counts the total number of records in the table.
    pub async fn count(ctx: &mut RequestContext) -> Result<i64, lightx::core::AppError> {
        let query = sqlx::query_scalar::<_, i64>(r#"SELECT COUNT(*) FROM users"#);
        let total = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_one(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_one(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(total)
    }

    /// Returns an asynchronous stream to process millions of records without allocating massive memory.
    pub fn stream_all<'a>(ctx: &'a mut RequestContext) -> std::pin::Pin<Box<dyn futures::Stream<Item = Result<Self, lightx::core::AppError>> + Send + 'a>> {
        let query = sqlx::query_as::<_, Self>(r#"SELECT `created_at`, `email`, `first_name`, `id`, `last_name`, `status` FROM users"#);
        use futures::StreamExt;
        if let Some(tx) = ctx.default_tx.as_mut() {
            let stream = query.fetch(&mut **tx).map(|res| res.map_err(|e| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() }));
            Box::pin(stream)
        } else {
            let stream = query.fetch(&ctx.default_pool).map(|res| res.map_err(|e| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() }));
            Box::pin(stream)
        }
    }

    /// Inserts multiple records in a single atomic transaction. (Batch Insert)
    pub async fn insert_many(items: &[Self], ctx: &mut RequestContext) -> Result<u64, lightx::core::AppError> {
        ctx.get_or_create_default_tx().await?;
        let mut count = 0;
        for item in items {
            item.insert(ctx).await?;
            count += 1;
        }
        Ok(count)
    }

    /// Upserts multiple records in a single atomic transaction. (Batch Upsert)
    pub async fn upsert_many(items: &[Self], ctx: &mut RequestContext) -> Result<(), lightx::core::AppError> {
        ctx.get_or_create_default_tx().await?;
        for item in items {
            item.upsert(ctx).await?;
        }
        Ok(())
    }

    /// Retrieves records by index `idx_name`.
    pub async fn get_by_last_name_and_first_name(ctx: &mut RequestContext, last_name: &str, first_name: &str) -> Result<Vec<Self>, lightx::core::AppError> {
        let mut query = sqlx::query_as(r#"SELECT `created_at`, `email`, `first_name`, `id`, `last_name`, `status` FROM users WHERE `last_name` = ? AND `first_name` = ?"#);
        query = query.bind(last_name);
        query = query.bind(first_name);
        let records = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_all(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_all(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(records)
    }

    /// Safely streams records by index `idx_name`.
    pub fn stream_by_last_name_and_first_name<'a>(ctx: &'a mut RequestContext, last_name: &'a str, first_name: &'a str) -> std::pin::Pin<Box<dyn futures::Stream<Item = Result<Self, lightx::core::AppError>> + Send + 'a>> {
        let mut query = sqlx::query_as::<_, Self>(r#"SELECT `created_at`, `email`, `first_name`, `id`, `last_name`, `status` FROM users WHERE `last_name` = ? AND `first_name` = ?"#);
        query = query.bind(last_name);
        query = query.bind(first_name);
        use futures::StreamExt;
        if let Some(tx) = ctx.default_tx.as_mut() {
            let stream = query.fetch(&mut **tx).map(|res| res.map_err(|e| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() }));
            Box::pin(stream)
        } else {
            let stream = query.fetch(&ctx.default_pool).map(|res| res.map_err(|e| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() }));
            Box::pin(stream)
        }
    }

    /// Deletes records matching the index `idx_name`.
    pub async fn delete_by_last_name_and_first_name(ctx: &mut RequestContext, last_name: &str, first_name: &str) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"DELETE FROM users WHERE `last_name` = ? AND `first_name` = ?"#);
        query = query.bind(last_name);
        query = query.bind(first_name);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    /// Retrieves records by index `idx_email`.
    pub async fn get_by_email(ctx: &mut RequestContext, email: &str) -> Result<Option<Self>, lightx::core::AppError> {
        let mut query = sqlx::query_as(r#"SELECT `created_at`, `email`, `first_name`, `id`, `last_name`, `status` FROM users WHERE `email` = ?"#);
        query = query.bind(email);
        let records = if let Some(tx) = ctx.default_tx.as_mut() {
            query.fetch_optional(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        } else {
            query.fetch_optional(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?
        };
        Ok(records)
    }

    /// Deletes records matching the index `idx_email`.
    pub async fn delete_by_email(ctx: &mut RequestContext, email: &str) -> Result<(), lightx::core::AppError> {
        let mut query = sqlx::query(r#"DELETE FROM users WHERE `email` = ?"#);
        query = query.bind(email);
        if let Some(tx) = ctx.default_tx.as_mut() {
            query.execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        } else {
            query.execute(&ctx.default_pool).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

}

