// =====================================================================
// THIS FILE IS AUTO-GENERATED BY LIGHTX. DO NOT EDIT.
// =====================================================================

pub struct RequestContext {
    pub raw_body: lightx::ext::bytes::Bytes,
    pub rate_limiter: std::sync::Arc<lightx::ext::moka::sync::Cache<(std::net::IpAddr, &'static str), std::sync::Arc<std::sync::atomic::AtomicU32>>>,
    pub response_cache: std::sync::Arc<lightx::ext::moka::sync::Cache<String, (lightx::ext::hyper::StatusCode, lightx::ext::hyper::HeaderMap, lightx::ext::bytes::Bytes, std::time::Instant)>>,
    pub client_ip: std::net::IpAddr,
    pub user_id: std::option::Option<String>,
    pub headers: lightx::ext::hyper::HeaderMap,
    pub default_pool: sqlx::MySqlPool,
    pub default_tx: Option<sqlx::Transaction<'static, sqlx::MySql>>,
}

pub struct AppContextFactory {
    pub rate_limiter: std::sync::Arc<lightx::ext::moka::sync::Cache<(std::net::IpAddr, &'static str), std::sync::Arc<std::sync::atomic::AtomicU32>>>,
    pub response_cache: std::sync::Arc<lightx::ext::moka::sync::Cache<String, (lightx::ext::hyper::StatusCode, lightx::ext::hyper::HeaderMap, lightx::ext::bytes::Bytes, std::time::Instant)>>,
    pub default_pool: sqlx::MySqlPool,
}

impl AppContextFactory {
    pub async fn new() -> Result<Self, lightx::core::AppError> {
        Ok(Self {
            rate_limiter: std::sync::Arc::new(lightx::ext::moka::sync::Cache::builder().build()),
            response_cache: std::sync::Arc::new(lightx::ext::moka::sync::Cache::builder().build()),
            default_pool: sqlx::mysql::MySqlPoolOptions::new().connect(&std::env::var("DEFAULT_DATABASE_URL").or_else(|_| std::env::var("DATABASE_URL")).unwrap_or_else(|_| "mysql://root:root@127.0.0.1:3306/my_database".to_string())).await.map_err(|e| lightx::core::AppError::SystemError { msg: e.to_string(), file: file!(), line: line!() })?,
        })
    }
}

impl lightx::server::ContextFactory for AppContextFactory {
    type Context = RequestContext;
    fn create_context(&self, peer_addr: std::net::IpAddr, headers: lightx::ext::hyper::HeaderMap, raw_body: lightx::ext::bytes::Bytes) -> Self::Context {
        let mut client_ip = peer_addr;
        if let Some(xff) = headers.get("x-forwarded-for") {
            if let Ok(s) = xff.to_str() {
                if let Some(first) = s.split(',').next() {
                    if let Ok(parsed) = first.trim().parse() { client_ip = parsed; }
                }
            }
        } else if let Some(xreal) = headers.get("x-real-ip") {
            if let Ok(s) = xreal.to_str() {
                if let Ok(parsed) = s.trim().parse() { client_ip = parsed; }
            }
        }
        RequestContext {
            raw_body,
            rate_limiter: self.rate_limiter.clone(),
            response_cache: self.response_cache.clone(),
            client_ip,
            user_id: None,
            headers,
            default_pool: self.default_pool.clone(),
            default_tx: None,
        }
    }
    fn commit_context<'a>(&'a self, ctx: &'a mut Self::Context) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<(), String>> + Send + 'a>> {
        Box::pin(async move {
            if let Some(tx) = ctx.default_tx.take() {
                tx.commit().await.map_err(|e| e.to_string())?;
            }
            Ok(())
        })
    }
}

impl RequestContext {
    pub async fn new_sandbox_context() -> Result<Self, lightx::core::AppError> {
        let mut ctx = Self {
            raw_body: lightx::ext::bytes::Bytes::new(),
            rate_limiter: std::sync::Arc::new(lightx::ext::moka::sync::Cache::builder().max_capacity(1).build()),
            response_cache: std::sync::Arc::new(lightx::ext::moka::sync::Cache::builder().max_capacity(1).build()),
            client_ip: "127.0.0.1".parse().unwrap(),
            user_id: None,
            headers: lightx::ext::hyper::HeaderMap::new(),
            default_pool: sqlx::mysql::MySqlPoolOptions::new().connect(&std::env::var("DEFAULT_DATABASE_URL").or_else(|_| std::env::var("DATABASE_URL")).unwrap_or_else(|_| "mysql://root:root@127.0.0.1:3306/my_database".to_string())).await.map_err(|e| lightx::core::AppError::SystemError { msg: e.to_string(), file: file!(), line: line!() })?,
            default_tx: None,
        };
        ctx.get_or_create_default_tx().await?;
        Ok(ctx)
    }

    pub async fn rollback_all_sandbox_tx(&mut self) -> Result<(), lightx::core::AppError> {
        self.rollback_default_tx().await?;
        Ok(())
    }

    pub async fn get_or_create_default_tx(&mut self) -> Result<&mut sqlx::Transaction<'static, sqlx::MySql>, lightx::core::AppError> {
        if self.default_tx.is_none() {
            let tx = self.default_pool.begin().await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
            self.default_tx = Some(tx);
        }
        self.default_tx.as_mut().ok_or_else(|| lightx::core::AppError::SystemError { msg: "Tx absent".to_string(), file: file!(), line: line!() })
    }

    pub async fn commit_default_tx(&mut self) -> Result<(), lightx::core::AppError> {
        if let Some(tx) = self.default_tx.take() {
            tx.commit().await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }

    pub async fn rollback_default_tx(&mut self) -> Result<(), lightx::core::AppError> {
        if let Some(tx) = self.default_tx.take() {
            tx.rollback().await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        }
        Ok(())
    }
}

#[derive(Debug, Clone, sqlx::FromRow)]
pub struct ActiveUsers {
    pub email: String,
    pub first_name: Option<String>,
    pub id: i64,
    pub last_name: String,
}

impl ActiveUsers {
    /// Inserts the current record. The BEGIN TRANSACTION is guaranteed by the RequestContext.
    pub async fn insert(&self, ctx: &mut crate::RequestContext) -> Result<u64, lightx::core::AppError> {
        let tx = ctx.get_or_create_default_tx().await?;
        let result = sqlx::query(r#"INSERT INTO active_users (`email`, `first_name`, `id`, `last_name`) VALUES (?, ?, ?, ?)"#)
        .bind(&self.email)
        .bind(&self.first_name)
        .bind(&self.id)
        .bind(&self.last_name)
        .execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        Ok(result.last_insert_id())
    }

}

#[derive(Debug, Clone, sqlx::FromRow)]
pub struct Configurations {
    pub id: i32,
    pub r#match: Option<String>,
    pub r#type: String,
    pub value: Option<String>,
}

impl Configurations {
    /// Inserts the current record. The BEGIN TRANSACTION is guaranteed by the RequestContext.
    pub async fn insert(&self, ctx: &mut crate::RequestContext) -> Result<u64, lightx::core::AppError> {
        let tx = ctx.get_or_create_default_tx().await?;
        let result = sqlx::query(r#"INSERT INTO configurations (`match`, `type`, `value`) VALUES (?, ?, ?)"#)
        .bind(&self.r#match)
        .bind(&self.r#type)
        .bind(&self.value)
        .execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        Ok(result.last_insert_id())
    }

    /// Retrieves a record via its primary key. SQL syntax validation at compile time.
    pub async fn get_by_pk(ctx: &mut crate::RequestContext, id: i32) -> Result<Option<Self>, lightx::core::AppError> {
        let tx = ctx.get_or_create_default_tx().await?;
        let record = sqlx::query_as(r#"SELECT * FROM configurations WHERE `id` = ?"#)
        .bind(&id)
        .fetch_optional(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        Ok(record)
    }

    /// Updates the entire record via its primary key.
    pub async fn update_by_pk(&self, ctx: &mut crate::RequestContext) -> Result<(), lightx::core::AppError> {
        let tx = ctx.get_or_create_default_tx().await?;
        sqlx::query(r#"UPDATE configurations SET `match` = ?, `type` = ?, `value` = ? WHERE `id` = ?"#)
        .bind(&self.r#match)
        .bind(&self.r#type)
        .bind(&self.value)
        .bind(&self.id)
        .execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        Ok(())
    }

    /// Permanently deletes the record.
    pub async fn delete_by_pk(ctx: &mut crate::RequestContext, id: i32) -> Result<(), lightx::core::AppError> {
        let tx = ctx.get_or_create_default_tx().await?;
        sqlx::query(r#"DELETE FROM configurations WHERE `id` = ?"#)
        .bind(&id)
        .execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        Ok(())
    }

}

#[derive(Debug, Clone, sqlx::FromRow)]
pub struct Currencies {
    pub code: String,
    pub name: String,
}

impl Currencies {
    /// Inserts the current record. The BEGIN TRANSACTION is guaranteed by the RequestContext.
    pub async fn insert(&self, ctx: &mut crate::RequestContext) -> Result<u64, lightx::core::AppError> {
        let tx = ctx.get_or_create_default_tx().await?;
        let result = sqlx::query(r#"INSERT INTO currencies (`code`, `name`) VALUES (?, ?)"#)
        .bind(&self.code)
        .bind(&self.name)
        .execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        Ok(result.last_insert_id())
    }

    /// Retrieves a record via its primary key. SQL syntax validation at compile time.
    pub async fn get_by_pk(ctx: &mut crate::RequestContext, code: String) -> Result<Option<Self>, lightx::core::AppError> {
        let tx = ctx.get_or_create_default_tx().await?;
        let record = sqlx::query_as(r#"SELECT * FROM currencies WHERE `code` = ?"#)
        .bind(&code)
        .fetch_optional(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        Ok(record)
    }

    /// Updates the entire record via its primary key.
    pub async fn update_by_pk(&self, ctx: &mut crate::RequestContext) -> Result<(), lightx::core::AppError> {
        let tx = ctx.get_or_create_default_tx().await?;
        sqlx::query(r#"UPDATE currencies SET `name` = ? WHERE `code` = ?"#)
        .bind(&self.name)
        .bind(&self.code)
        .execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        Ok(())
    }

    /// Permanently deletes the record.
    pub async fn delete_by_pk(ctx: &mut crate::RequestContext, code: String) -> Result<(), lightx::core::AppError> {
        let tx = ctx.get_or_create_default_tx().await?;
        sqlx::query(r#"DELETE FROM currencies WHERE `code` = ?"#)
        .bind(&code)
        .execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        Ok(())
    }

}

#[derive(Debug, Clone, sqlx::FromRow)]
pub struct OrderItems {
    pub order_id: i64,
    pub product_id: i64,
    pub quantity: i32,
}

impl OrderItems {
    /// Inserts the current record. The BEGIN TRANSACTION is guaranteed by the RequestContext.
    pub async fn insert(&self, ctx: &mut crate::RequestContext) -> Result<u64, lightx::core::AppError> {
        let tx = ctx.get_or_create_default_tx().await?;
        let result = sqlx::query(r#"INSERT INTO order_items (`order_id`, `product_id`, `quantity`) VALUES (?, ?, ?)"#)
        .bind(&self.order_id)
        .bind(&self.product_id)
        .bind(&self.quantity)
        .execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        Ok(result.last_insert_id())
    }

    /// Retrieves a record via its primary key. SQL syntax validation at compile time.
    pub async fn get_by_pk(ctx: &mut crate::RequestContext, order_id: i64, product_id: i64) -> Result<Option<Self>, lightx::core::AppError> {
        let tx = ctx.get_or_create_default_tx().await?;
        let record = sqlx::query_as(r#"SELECT * FROM order_items WHERE `order_id` = ? AND `product_id` = ?"#)
        .bind(&order_id)
        .bind(&product_id)
        .fetch_optional(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        Ok(record)
    }

    /// Updates the entire record via its primary key.
    pub async fn update_by_pk(&self, ctx: &mut crate::RequestContext) -> Result<(), lightx::core::AppError> {
        let tx = ctx.get_or_create_default_tx().await?;
        sqlx::query(r#"UPDATE order_items SET `quantity` = ? WHERE `order_id` = ? AND `product_id` = ?"#)
        .bind(&self.quantity)
        .bind(&self.order_id)
        .bind(&self.product_id)
        .execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        Ok(())
    }

    /// Permanently deletes the record.
    pub async fn delete_by_pk(ctx: &mut crate::RequestContext, order_id: i64, product_id: i64) -> Result<(), lightx::core::AppError> {
        let tx = ctx.get_or_create_default_tx().await?;
        sqlx::query(r#"DELETE FROM order_items WHERE `order_id` = ? AND `product_id` = ?"#)
        .bind(&order_id)
        .bind(&product_id)
        .execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        Ok(())
    }

}

#[derive(Debug, Clone, sqlx::FromRow)]
pub struct ProductMetadata {
    pub attributes: Option<String>,
    pub category: String,
    pub id: Vec<u8>,
    pub raw_data: Option<Vec<u8>>,
}

impl ProductMetadata {
    /// Inserts the current record. The BEGIN TRANSACTION is guaranteed by the RequestContext.
    pub async fn insert(&self, ctx: &mut crate::RequestContext) -> Result<u64, lightx::core::AppError> {
        let tx = ctx.get_or_create_default_tx().await?;
        let result = sqlx::query(r#"INSERT INTO product_metadata (`attributes`, `category`, `id`, `raw_data`) VALUES (?, ?, ?, ?)"#)
        .bind(&self.attributes)
        .bind(&self.category)
        .bind(&self.id)
        .bind(&self.raw_data)
        .execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        Ok(result.last_insert_id())
    }

    /// Retrieves a record via its primary key. SQL syntax validation at compile time.
    pub async fn get_by_pk(ctx: &mut crate::RequestContext, id: Vec<u8>) -> Result<Option<Self>, lightx::core::AppError> {
        let tx = ctx.get_or_create_default_tx().await?;
        let record = sqlx::query_as(r#"SELECT * FROM product_metadata WHERE `id` = ?"#)
        .bind(&id)
        .fetch_optional(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        Ok(record)
    }

    /// Updates the entire record via its primary key.
    pub async fn update_by_pk(&self, ctx: &mut crate::RequestContext) -> Result<(), lightx::core::AppError> {
        let tx = ctx.get_or_create_default_tx().await?;
        sqlx::query(r#"UPDATE product_metadata SET `attributes` = ?, `category` = ?, `raw_data` = ? WHERE `id` = ?"#)
        .bind(&self.attributes)
        .bind(&self.category)
        .bind(&self.raw_data)
        .bind(&self.id)
        .execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        Ok(())
    }

    /// Permanently deletes the record.
    pub async fn delete_by_pk(ctx: &mut crate::RequestContext, id: Vec<u8>) -> Result<(), lightx::core::AppError> {
        let tx = ctx.get_or_create_default_tx().await?;
        sqlx::query(r#"DELETE FROM product_metadata WHERE `id` = ?"#)
        .bind(&id)
        .execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        Ok(())
    }

}

#[derive(Debug, Clone, sqlx::FromRow)]
pub struct UserRoles {
    pub assigned_at: Option<chrono::DateTime<chrono::Utc>>,
    pub role_name: String,
    pub user_id: i64,
}

impl UserRoles {
    /// Inserts the current record. The BEGIN TRANSACTION is guaranteed by the RequestContext.
    pub async fn insert(&self, ctx: &mut crate::RequestContext) -> Result<u64, lightx::core::AppError> {
        let tx = ctx.get_or_create_default_tx().await?;
        let result = sqlx::query(r#"INSERT INTO user_roles (`assigned_at`, `role_name`, `user_id`) VALUES (?, ?, ?)"#)
        .bind(&self.assigned_at)
        .bind(&self.role_name)
        .bind(&self.user_id)
        .execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        Ok(result.last_insert_id())
    }

    /// Retrieves a record via its primary key. SQL syntax validation at compile time.
    pub async fn get_by_pk(ctx: &mut crate::RequestContext, role_name: String, user_id: i64) -> Result<Option<Self>, lightx::core::AppError> {
        let tx = ctx.get_or_create_default_tx().await?;
        let record = sqlx::query_as(r#"SELECT * FROM user_roles WHERE `role_name` = ? AND `user_id` = ?"#)
        .bind(&role_name)
        .bind(&user_id)
        .fetch_optional(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        Ok(record)
    }

    /// Updates the entire record via its primary key.
    pub async fn update_by_pk(&self, ctx: &mut crate::RequestContext) -> Result<(), lightx::core::AppError> {
        let tx = ctx.get_or_create_default_tx().await?;
        sqlx::query(r#"UPDATE user_roles SET `assigned_at` = ? WHERE `role_name` = ? AND `user_id` = ?"#)
        .bind(&self.assigned_at)
        .bind(&self.role_name)
        .bind(&self.user_id)
        .execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        Ok(())
    }

    /// Permanently deletes the record.
    pub async fn delete_by_pk(ctx: &mut crate::RequestContext, role_name: String, user_id: i64) -> Result<(), lightx::core::AppError> {
        let tx = ctx.get_or_create_default_tx().await?;
        sqlx::query(r#"DELETE FROM user_roles WHERE `role_name` = ? AND `user_id` = ?"#)
        .bind(&role_name)
        .bind(&user_id)
        .execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        Ok(())
    }

}

#[derive(Debug, Clone, sqlx::FromRow)]
pub struct Users {
    pub created_at: Option<chrono::DateTime<chrono::Utc>>,
    pub email: String,
    pub first_name: Option<String>,
    pub id: i64,
    pub last_name: String,
    pub status: String,
}

impl Users {
    /// Inserts the current record. The BEGIN TRANSACTION is guaranteed by the RequestContext.
    pub async fn insert(&self, ctx: &mut crate::RequestContext) -> Result<u64, lightx::core::AppError> {
        let tx = ctx.get_or_create_default_tx().await?;
        let result = sqlx::query(r#"INSERT INTO users (`created_at`, `email`, `first_name`, `last_name`, `status`) VALUES (?, ?, ?, ?, ?)"#)
        .bind(&self.created_at)
        .bind(&self.email)
        .bind(&self.first_name)
        .bind(&self.last_name)
        .bind(&self.status)
        .execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        Ok(result.last_insert_id())
    }

    /// Retrieves a record via its primary key. SQL syntax validation at compile time.
    pub async fn get_by_pk(ctx: &mut crate::RequestContext, id: i64) -> Result<Option<Self>, lightx::core::AppError> {
        let tx = ctx.get_or_create_default_tx().await?;
        let record = sqlx::query_as(r#"SELECT * FROM users WHERE `id` = ?"#)
        .bind(&id)
        .fetch_optional(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        Ok(record)
    }

    /// Updates the entire record via its primary key.
    pub async fn update_by_pk(&self, ctx: &mut crate::RequestContext) -> Result<(), lightx::core::AppError> {
        let tx = ctx.get_or_create_default_tx().await?;
        sqlx::query(r#"UPDATE users SET `created_at` = ?, `email` = ?, `first_name` = ?, `last_name` = ?, `status` = ? WHERE `id` = ?"#)
        .bind(&self.created_at)
        .bind(&self.email)
        .bind(&self.first_name)
        .bind(&self.last_name)
        .bind(&self.status)
        .bind(&self.id)
        .execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        Ok(())
    }

    /// Permanently deletes the record.
    pub async fn delete_by_pk(ctx: &mut crate::RequestContext, id: i64) -> Result<(), lightx::core::AppError> {
        let tx = ctx.get_or_create_default_tx().await?;
        sqlx::query(r#"DELETE FROM users WHERE `id` = ?"#)
        .bind(&id)
        .execute(&mut **tx).await.map_err(|e: sqlx::Error| lightx::core::AppError::DatabaseError { msg: e.to_string(), file: file!(), line: line!() })?;
        Ok(())
    }

}

