[package]
name = "daox"
version = "0.1.0"
edition = "2021"
authors = ["Vincent SOYSOUVANH <vincent.soysouvanh@gmail.com>"]
description = "Générateur DAO Database-first orienté performance extrême"


[dependencies]
# Introspection DB (MySQL/MariaDB + PostgreSQL)
sqlx = { version = "0.8", features = [
    "mysql",
    "postgres",
    "sqlite",
    "runtime-tokio-rustls",
] }
tokio = { version = "1", features = ["full"] }

# Conversion des noms (ex: snake_case -> PascalCase pour les structs)
heck = "0.5"

# Gestion propre des erreurs
anyhow = "1.0"
